#!/bin/bash

cd ~/GitHub/adb_final_project/adb_final/adb_final_proj/src

javac *.java
rm ~/Desktop/Tests/TestActual/Actual_Test*.txt
for i in {0..20}; 
do 
echo '---------------------------------'; 
echo 'Test' $i;
echo '---------------------------------'; 
touch ~/Desktop/Tests/TestActual/Actual_Test_$i.txt

java ExecuteTransactions ~/GitHub/adb_final_project/adb_final/adb_final_proj/projectsampletests$i.txt >> ~/Desktop/Tests/TestActual/Actual_Test_$i.txt;
java ExecuteTransactions ~/GitHub/adb_final_project/adb_final/adb_final_proj/projectsampletests$i.txt
done
rm *.class

for x in {0..20}; 
do 
echo '---------------------------------'; 
echo 'Test' $x;
echo '---------------------------------'; 
diff ~/Desktop/Tests/TestActual/Actual_Test_$x.txt ~/Desktop/Tests/TestExpected/Expected_Test_$x.txt
done